### PR TITLE
Modified Sample application to support MultiShardQuery in Dam project

### PR DESCRIPTION
**Pull request by supragyan**
Modified following in Azure Elastic Sample application.
- Created  MultiShardQuerySupport class to support MultiShardQuery functionality in Dam project.
- Created LayerB and LayerD class to implement the Select method.
- Created TestParameterValue.cs,TestReturnValue.cs class to pass the required parameters to  Framework project

### CODE REVIEW

**Comment by daisukenishino** [comment]
@supragyan 

It is great that this can corespond with dam by slight modification. However, there is one problem that I want to add this sample as new one as ElasticScaleStarterKit2 rather than as a change of ElasticScaleStarterKit.

Modifications to this will continue because there are https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/146/ modifications.

**Comment by supragyan** [comment]
@daisukenishino 

\>It is great that this can corespond with dam by slight modification.
Thank you for confirmation.

\>But, I have one question.
\>Is this the sample can be operated by the same procedure as the original sample?
Yes this the sample can be operated by the same procedure as the original sample.
We have added MultiShardQuery execution with our Dam project in same existing sample because till yet we have not implemented DataDependentRouting for creating Shards.

\>\>If so, there is one additional request that I want to add this sample as new one as ElasticScaleStarterKit2 rather than as a change of ElasticScaleStarterKit.
Ok.We will create separate sample as ElasticScaleStarterKit2 which will contain only MultiShardQuery functionality.

Is this ok?

Please confirm.

**Comment by daisukenishino** [comment]
@supragyan 

>https://github.com/SymphonyTeleca/SampleProgram/pull/20#issuecomment-214970024

Please add processing of creating Shards and executeing DataDependentRouting and MultiShardQuery to ElasticScaleStarterKit2.

**Comment by supragyan** [comment]
@daisukenishino 

\>Please add processing of creating shards and executeing DataDependentRouting and MultiShardQuery to ElasticScaleStarterKit2.

Ok.
Now we will move MultiShardQuery functionality to newly created ElasticScaleStarterKit2 project.
We started to work on  DataDependentRouting in ElasticScaleStarterKit2 project.
Once it is done we will deliver this sample with both functionalty..

**Pull request closed without merging**
