### PR TITLE
Translate api

### PR DESCRIPTION
**Pull request by supragyan**
Implemented sapmle of Translate API.

### CODE REVIEW

**Comment by daisukenishino** [comment]
Please build the environment to Azure Iaas.
We will check this by perform the operation.

**Comment by supragyan** [comment]
Sure Nishino-San

**Comment by supragyan** [comment]
@daisukenishino 

As per your comment in mail
>We want to select the culture of the FROM and TO.
>I think it's a fixed value currently.
HODC wants to confirm:
Do we need to implement like Google Translator?
means If  user enters some text in 'English language' in Enter Textbox and choose one language (eg:Japanese) from 'FROM' dropdownlist then it will be translated to Japanese language and displaying in  Translated TextBox?

HODC poposal:
Instead of 'FROM' dropdownlist we can implement Detect method functionality of Microsoft Translate API .
Because Microsoft Translate API can auto detect the language of browser supported language.So no need to implement FROM dropdownlist.

**Comment by daisukenishino** [comment]
@supragyan 

Native language of the user is not necessarily the same as the language set in the browser.
I think that there is the reason because that most of the translation service specify the "FROM" and "TO".
Therefore you will need a selection in the DropDown, Even if there is a auto detect the language function.
This is useful in testing.

**Pull request merged**
