### PR TITLE
Resolved missing packages and project related files while performing commit.

### PR DESCRIPTION
**Pull request by supragyan**
Resolved missing packages and project related files while performing commit.

### CODE REVIEW

**Comment by daisukenishino** [comment]
@supragyan 

Please explain what has been changed.

>Resolved missing packages and project related files while performing commit. #10 

It is not enough in this title.

It looks like there is other changes other than packages.
What are the problems of the previous pull request ?

**Comment by supragyan** [comment]
@daisukenishino 

\>\>It looks like there is other changes other than packages.
\>\>What are the problems of the previous pull request ?

We committed the missing file in SignalRChatNew branch.
Then we pulled from latest SignalRChatNew branch and tested.
Then we found shift js encoded format problem.
So we converted ANSI format to UTF-8 format and tested.

Then we created pull request with changed of packages format.

Is this ok?
Please let us know.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>Is this ok?

Whether the completeness of this sample is enough ?
Also, whether this sample is tested enough ?

Did you confirm that there is no problem in the implementation
  by to perform demonstration and briefing within the team?

Since I do not have time to check in detail, I want you to tell me about the above.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
We found javascript issues while testing in internet explorer 9.
We fixed these issues and did code commit.
Please close this pull request to create new pull request.

**Pull request merged**
