### PR TITLE
Created Azure Elastic Sample Application with MultiShard and DataDependentRouting

### PR DESCRIPTION
**Pull request by supragyan**
Implemented Azure Elastic Sample Application with MultiShard and DataDependentRouting

### CODE REVIEW

**Comment by daisukenishino** [comment]
@supragyan 

I confirmed this pullrequest.
The following is a note of the changes.

### No changed
- .nuget/
  - NuGet.Config
  - NuGet.exe
  - NuGet.targets
- ElasticScaleStarterKit2/
  - InitializeShard.sql

### Changed
- ElasticScaleStarterKit2/
  - Program.cs  
This was rewritten to use the OpenTouryo.

##### A little changed
- ElasticScaleStarterKit2/
  - app.config  
Method of setting the connection string and any other have been changed.
  - SqlDatabaseUtils.cs  
Method of getting the connection string and any other have been changed.
  - CreateShardSample.cs  
    - Changed the header and namespace and module name.  
    - name was changed as "MultiShardConfiguration" from "Configuration".

##### Rewritten
- ElasticScaleStarterKit2/
  - MultiShardQuerySupport.cs  
This is rewrited the MultiShardQuerySample.cs. 
  - DataDependentRoutingSupport.cs  
This is rewrited the DataDependentRoutingSample.cs.

##### Changed the header and namespace.
- ElasticScaleStarterKit2/
  - ConsoleUtils.cs
  - ShardManagementUtils.cs
  - TableFormatter.cs

### Added
##### OpenTouryo
- ElasticScaleStarterKit2/
  - LayerB.cs
  - LayerD.cs
  - TestParameterValue.cs
  - TestReturnValue.cs

**Comment by daisukenishino** [comment]
@supragyan 

The following is pointed out from me.

### path
```
ElasticDatabase\ElasticScaleStarterKit2\ElasticScaleStarterKit2
```
▼ ▼ ▼
```
ElasticDatabase\ElasticDB_Sample2\ElasticScaleStarterKit
```

### namespace
Please return to the original.
```
namespace ElasticScaleStarterKit2
```
▼ ▼ ▼
```
namespace ElasticScaleStarterKit
```
### header
Please leave a following description of the copyright and license.

- copyright and license
```CS
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
```
- Target of modules  
These modules are changed slight.
  - CreateShardSample.cs
  - ConsoleUtils.cs
  - TableFormatter.cs
  - SqlDatabaseUtils.cs
  - ShardManagementUtils.cs

### Else
- AssemblyInfo.cs  
see : https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/42c20a718093ce97414c0ae6d3f6d3d2958cdc1e/root_VS2012/programs/C%23/Frameworks/Infrastructure/Public/Db/DamSqlDbWithMultiShard/DamSqlDbWithMultiShard/Properties/AssemblyInfo.cs

**Comment by supragyan** [comment]
@daisukenishino 

Shall we add [this copyright](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/42c20a718093ce97414c0ae6d3f6d3d2958cdc1e/root_VS2012/programs/C%23/Frameworks/Infrastructure/Public/Db/DamSqlDbWithMultiShard/DamSqlDbWithMultiShard/Properties/AssemblyInfo.cs#L2) in below files.
 - CreateShardSample.cs
 - ConsoleUtils.cs
 - TableFormatter.cs
 - SqlDatabaseUtils.cs
 - ShardManagementUtils.cs

or do we need to add below microsoft copyright
 ```CS
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
```

Please confirm.

**Comment by daisukenishino** [comment]
@supragyan 

Please add "microsoft copyright".
This is because, these modules have kept the  original form.

**Comment by supragyan** [comment]
@daisukenishino 

We have modified copyright [here](https://github.com/SymphonyTeleca/SampleProgram/pull/21/commits/38346b45b76db2358bec2fc4a8b9618ea0876205#diff-cd128b3430e318211bc08515e21d2293R1) as per your pointed out.

Please review.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Reopened this pull request, because to remove the code commit log that had usename and password.
Now, that history has been removed and closing this pull request.

**Pull request closed without merging**
