### PR TITLE
Added MIT sample for demonstrating Azure Elastic Database

### PR DESCRIPTION
**Pull request by supragyan**
Implemented code to create Windows Azure SQL database
Implemented code to connect with SQL database and inserting sample rows in DataDependent Routing class
Implemented code to Select the sample rows from database in MultiShardQuery class using MultishardConnection, MultishardCommand, MultishardDataReader class.

### CODE REVIEW

**Comment by daisukenishino** [comment]
@supragyan 

```TXT
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
```
I couldn’t found LICENSE file.
LICENSE file did not exist at project root ?

**Comment by daisukenishino** [comment]
@supragyan 

Does this program is get from nuget as follows?
http://go.microsoft.com/fwlink/?LinkID=510913

**Comment by supragyan** [comment]
@daisukenishino 

>>I couldn’t found LICENSE file.
>>LICENSE file did not exist at project root ?

Yes Nishino-San,LICENSE file has removed from project root.
It means when we downloded only License reference is showing but file has removed.

**Comment by supragyan** [comment]
@daisukenishino 

>>Does this program is get from nuget as follows?
>>http://go.microsoft.com/fwlink/?LinkID=510913

No This program is not created from Nuget.
Yes we followed above link but 
we got this project from Visual Studio-->New project-->Online.

Thanks & Regards,

**Comment by daisukenishino** [comment]
@supragyan 

>https://github.com/SymphonyTeleca/SampleProgram/pull/19#issuecomment-191145972
https://github.com/SymphonyTeleca/SampleProgram/pull/19#issuecomment-191152211

I see.

However, These result of research and sample program are also off-the-shelf.

see : https://github.com/OpenTouryoProject/OpenTouryo/issues/144#issuecomment-191194882

Since the meeting is necessary, I will request a meeting to 14:00 IST on March 4th.

Is it possible?

**Comment by supragyan** [comment]
@daisukenishino 

\>\>Since the meeting is necessary, I request to hold a meeting to 14:00 IST on March 4th.
\>\>Is it possible?
Yes Nishino-San.It is possible.

Regards,

**Pull request merged**
